[icons]
name = "awesome"

[[block]]
block = "net"
device = "wlp2s0"
format = "{ip} {signal_strength}"

[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "time"
interval = 1
format = "%D %r"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
