icons = "awesome"

[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "time"
interval = 1
format = "%D %r"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
