[icons]
name = "awesome"

[[block]]
block = "net"
device = "wlp2s0"
format = "{ip} {signal_strength}"

[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "sound"
driver = "pulseaudio"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = "%D %r"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "gtk-launch com.spotify.Client"
dynamic_width = true
max_width = 25
