[default.files]
alacritty = "~/.config/alacritty"
fish = "~/.config/fish"
fontconfig = "~/.config/fontconfig"
gdb = "~/.config/gdb"
git = "~/.config/git"
i3status-rs = "~/.config/i3status-rs"
imv = "~/.config/imv"
mako = "~/.config/mako"
mpv = "~/.config/mpv"
nvim = "~/.config/nvim"
tmux = "~/.config/tmux"
noncompliant_xdg = "~/.config"

[sway.files]
sway = "~/.config/sway"
swaylock = "~/.config/swaylock"
